server:
  port: 8085
  cors:
    allowed-origins: "*"
    allowed-methods: "GET, POST, PUT, DELETE"
    allowed-headers: "*"
    allow-credentials: false
    max-age: 3600

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/voter_db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: VOTER-SERVICE
  config:
    import: configserver:http://localhost:9296



# BELOW CONFIGURATION IS NOT NOW BEING FETCHED FROM CONFIG SERVER SERVICE
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

